### ISSUE TITLE
Это дожно быть const

### ISSUE THREAD

**Issue by coursar** [karpenkoea/HW-tinkoff-cashback#1]
https://github.com/karpenkoea/HW-tinkoff-cashback/blob/4366d7fe97af5ce793b85f2388b2072eb3af06bd/app.js#L3-L8

**Comment by karpenkoea** [comment]
Извините, но ведь первые три переменные изменяемые (не постоянные). Покупки могу быть изменяемыми.

**Comment by coursar** [comment]
На конкретный момент времени - они не изменяемы.
